'use strict';

var fs = require('fs');
var init = require('../src/commands/init');
var Clifier = require("clifier");

exports.testInit = function(test) {
    test.expect(2);

    Clifier.helpers.log.write = function() {}; // prevent console.log to show up
    
    test.ok(init());
    test.equal(init(), false); //file exists so don't need to be recreated

    //remove setitup.config test file generated by init command
    fs.unlinkSync(process.cwd() + '/setitup.config');

    test.done();
};