'use strict';

var fs = require('fs');
var currentDir = process.cwd();

module.exports = function(){
    if (fs.existsSync(currentDir+'/setitup.config')) {
        console.log("The file setitup.config already exists");
    } else {
        var fileContent = ""+
            "##########################################\r\n" +
            "### This file was generated by SetItUp ###\r\n" +
            "##########################################\r\n" +
            "\r\n" +
            "[project]\r\n" +
            "git = \"your git url\"\r\n" +
            "host = \"dev.psm.com\"\r\n" +
            "\r\n" +
            "[database]\r\n" +
            "type =        \"your database driver\"\r\n" +
            "name =        \"test\"\r\n" +
            "user =        \"root\"\r\n" +
            "password =    \"azerty\"\r\n" +
            "\r\n" +
            "[gem]\r\n" +
            "sass = \"--pre\"\r\n" +
            "compass\r\n" +
            "\r\n" +
            "[npm]\r\n" +
            "coffee-script = \">1.1 && <1.1\"\r\n" +
            "bower\r\n" +
            "requirejs\r\n" +
            "brunch\r\n" +
            "\r\n" +
            "[commands]\r\n" +
            "before = [\"php composer.phar install --dev\"]\r\n" +
            "after = [\"php app/console assets:install, \"php app/console cache:clear\"\"] \r\n";

        fs.writeFileSync(currentDir+'/setitup.config', fileContent);
    }
};